import { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { ContainerDiv, SeparatorDiv } from '@/styles/indexStyle'
import { BsFileEarmarkText } from 'react-icons/bs'
import { GoFileDirectory } from 'react-icons/go'
import { GiCrossedAxes } from 'react-icons/gi'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ContainerDiv>
          <header>
            <BsFileEarmarkText />
            <GoFileDirectory />

            <SeparatorDiv />

            <input type="text" placeholder="Build exotica abuh" />

            <button>salvar</button>

            <GiCrossedAxes />

            <span>CALCULADORA</span>
            <span>NEW WORLD BRASIL</span>
          </header>
        </ContainerDiv>
      </main>
    </div>
  )
}

export default Home
