import { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
  ContainerDiv,
  SeparatorDiv,
  Header,
  DirectoryDiv,
  SaveButton,
  IconButton,
  AxeDiv,
  NewWorldLogoSVG,
  AxeSpan,
  SeparatorHorizontal,
  PointsDiv,
  PointsDivSpan,
  PointsSpanName,
  PointsSpanValue,
  PointsInput,
  PointsSpanStr,
  PointsInputSlider,
} from '@/styles/indexStyle'
import { BsFileEarmarkText } from 'react-icons/bs'
import { GoFileDirectory } from 'react-icons/go'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ContainerDiv>
          <Header>
            <DirectoryDiv className="flex w-1/2 items-center">
              <IconButton marginRight="1rem">
                <BsFileEarmarkText />
              </IconButton>

              <IconButton>
                <GoFileDirectory />
              </IconButton>

              <SeparatorDiv />

              <input type="text" placeholder="Build exotica abuh" />

              <SaveButton>salvar</SaveButton>
            </DirectoryDiv>

            <div className="flex w-1/3 items-center">
              <NewWorldLogoSVG />

              <AxeDiv className="flex flex-col">
                <AxeSpan>calculadora</AxeSpan>
                <span>new world brasil</span>
              </AxeDiv>
            </div>
          </Header>

          <SeparatorHorizontal />

          <PointsDiv>
            <PointsDivSpan>
              <PointsSpanName>Pontos disponíveis</PointsSpanName>
              <PointsSpanValue>135</PointsSpanValue>
            </PointsDivSpan>

            <div className="flex mt-4 items-center">
              <PointsInput type="text" value="55" />
              <div className="flex flex-col w-full">
                <PointsSpanStr>força</PointsSpanStr>
                <PointsInputSlider type="range" step={50} min={0} max={400} />
              </div>
            </div>
          </PointsDiv>
        </ContainerDiv>
      </main>
    </div>
  )
}

export default Home
